name: perplexity_guide
description: "Guide complet Perplexity AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  http: ^1.2.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
